name: Publish Python Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install project dependencies
        run: |
          poetry install

      - name: Set up PyPI token
        run: |
          echo "//pypi.org/simple/ ${{ secrets.API_TOKEN }}" > ~/.config/pip/pip.conf

      - name: Build package
        run: |
          poetry build

      - name: Publish to PyPI
        run: |
          poetry publish --build